
import React, { useRef, useState } from 'react';
import { UserInfo, Difficulty } from '../types';
import Button from './Button';

interface DashboardProps {
  user: UserInfo;
  onStartQuiz: (difficulty: Difficulty, topic: string) => void;
  onFileUpload: (file: File) => void;
  onLogout: () => void;
  onOpenKmuPortal: () => void;
  isUploading: boolean;
  uploadProgress: number;
}

const Dashboard: React.FC<DashboardProps> = ({ 
  user, onStartQuiz, onFileUpload, onLogout, onOpenKmuPortal, isUploading, uploadProgress 
}) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [difficulty, setDifficulty] = useState<Difficulty>('Clinical');
  const [topic, setTopic] = useState('');

  return (
    <div className="max-w-[1400px] w-full flex flex-col gap-10 p-6 md:p-10 fade-in duration-700">
      {/* Header Profile Section */}
      <header className="bg-white/80 backdrop-blur-xl p-10 md:p-14 rounded-[4rem] shadow-[0_32px_64px_-16px_rgba(0,0,0,0.05)] border border-white/50 flex flex-col lg:flex-row items-center justify-between gap-10">
        <div className="flex items-center gap-10">
          <div className="w-24 h-24 bg-gradient-to-tr from-blue-600 to-indigo-500 rounded-[2.5rem] flex items-center justify-center shadow-2xl shadow-blue-200 text-white text-4xl font-black">
            {user.name[0]}
          </div>
          <div>
            <span className="text-[10px] font-black uppercase tracking-[0.3em] text-blue-600 bg-blue-50 px-3 py-1 rounded-full">Candidate Session</span>
            <h1 className="text-5xl font-extrabold text-slate-900 tracking-tight leading-none mt-2">Dr. {user.name}</h1>
            <p className="text-slate-400 font-semibold mt-2 text-lg">{user.category} • {user.year}</p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" onClick={onLogout} className="text-red-400">Logout</Button>
          <Button onClick={onOpenKmuPortal} variant="secondary" className="px-10">Archive Portal</Button>
        </div>
      </header>

      {/* Feature Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
        {/* AI LAB CARD */}
        <div className="bg-white p-12 rounded-[3.5rem] shadow-[0_20px_50px_-12px_rgba(0,0,0,0.03)] border border-slate-50 flex flex-col group hover:shadow-[0_40px_80px_-20px_rgba(0,0,0,0.08)] transition-all duration-500">
          <h2 className="text-3xl font-black mb-3 text-slate-900">AI Exam Lab</h2>
          <p className="text-slate-400 font-medium mb-10 text-sm">Targeted high-yield exams generated by neural networks.</p>
          
          <div className="space-y-4 mb-10">
            <input 
              type="text" placeholder="Topic (e.g., Cardiology)" 
              className="w-full bg-slate-50 p-5 rounded-2xl outline-none font-bold text-sm border-2 border-transparent focus:border-blue-500 transition-all"
              value={topic} onChange={(e) => setTopic(e.target.value)}
            />
            <div className="flex p-1.5 bg-slate-100 rounded-[1.5rem]">
              {(['Standard', 'Clinical', 'Elite'] as Difficulty[]).map(d => (
                <button 
                  key={d} onClick={() => setDifficulty(d)} 
                  className={`flex-1 py-3 text-[9px] font-black uppercase tracking-widest rounded-xl transition-all ${difficulty === d ? 'bg-white text-blue-600 shadow-md' : 'text-slate-400'}`}
                >
                  {d}
                </button>
              ))}
            </div>
          </div>
          <Button disabled={!topic.trim()} onClick={() => onStartQuiz(difficulty, topic)} variant="primary" className="mt-auto py-5">Launch Exam</Button>
        </div>

        {/* CLOUD ARCHIVE CARD */}
        <div onClick={onOpenKmuPortal} className="group bg-slate-950 p-12 rounded-[3.5rem] shadow-2xl text-white flex flex-col cursor-pointer hover:translate-y-[-8px] transition-all duration-500">
          <h2 className="text-3xl font-black mb-3">KMU Archive</h2>
          <p className="text-slate-400 font-medium mb-12 opacity-80 text-sm">Worldwide repository of verified professional papers.</p>
          <div className="mt-auto flex items-center justify-between">
            <span className="text-[10px] font-black uppercase tracking-widest text-blue-500">